/**
 * Full-screen help overlay.
 *
 * Screenshots are generated by running `npm run screenshots` and committed
 * to public/screenshots/.  See e2e/screenshots.spec.js for the update process.
 */

const BASE = import.meta.env.BASE_URL

function HelpImage({ src, alt }) {
  return (
    <div className="help-img-wrap">
      <img
        src={`${BASE}screenshots/${src}`}
        alt={alt}
        className="help-img"
        onError={e => {
          e.currentTarget.style.display = 'none'
          e.currentTarget.nextElementSibling.style.display = 'flex'
        }}
      />
      <div className="help-img-placeholder" style={{ display: 'none' }}>
        <span>📷</span>
        <span>Run <code>npm run screenshots</code> to generate help images</span>
      </div>
    </div>
  )
}

const SECTIONS = [
  {
    id: 'setup',
    title: '1 · Getting started',
    screenshot: { src: 'setup.png', alt: 'Setup screen showing event search and team number input' },
    content: (
      <>
        <p>When you first open the app you land on the <strong>Setup screen</strong>.</p>
        <ol>
          <li>Type your event code (e.g. <code>2026waspk</code>) or a few letters of the event name in the search box and select the matching event from the dropdown.</li>
          <li>Enter your assigned team numbers — one per line, or comma-separated.</li>
          <li>Green chips appear as each number is validated against the event roster. Unknown numbers show in orange.</li>
          <li>Tap <strong>Load Schedule</strong> to fetch match times from The Blue Alliance.</li>
        </ol>
        <p className="help-tip">💾 Your event and teams are saved automatically — reloading the page restores them.</p>
        <p className="help-tip">✏️ Tap <strong>Edit</strong> in the header at any time to correct the event or team list.</p>
      </>
    ),
  },
  {
    id: 'team-view',
    title: '2 · Team View',
    screenshot: { src: 'team-view.png', alt: 'Team view showing match blocks and green available windows on a vertical timeline' },
    content: (
      <>
        <p>Select a team from the dropdown to see their full-day timeline.</p>
        <ul>
          <li><strong>Grey blocks</strong> — match time or buffer before/after a match (team is unavailable).</li>
          <li><strong>Green blocks</strong> — windows long enough for an interview (at least 15 min by default).</li>
        </ul>
        <p>Check <strong>Interviewed ✓</strong> once you've visited the team. They move to the back of the dropdown so you can focus on remaining teams.</p>
      </>
    ),
  },
  {
    id: 'merged-view',
    title: '3 · Merged View',
    screenshot: { src: 'merged-view.png', alt: 'Merged view showing colour-coded 10-minute blocks with team counts' },
    content: (
      <>
        <p>The <strong>Merged tab</strong> breaks the day into 10-minute blocks and shows which of your remaining teams are free in each window. Blocks whose start time has passed are dimmed.</p>
        <ul>
          <li><strong>Deep red</strong> — no teams available (everyone in a match or buffer).</li>
          <li><strong>Amber / yellow</strong> — only one or two teams free.</li>
          <li><strong>Green</strong> — most or all remaining teams free.</li>
        </ul>
        <p>Blocks with identical available teams are merged into a single taller unit. Tap any block to reveal the team numbers on the right; interviewed teams appear with a strikethrough and are excluded from the count.</p>
        <p><strong>💡 Key strategy — target the amber blocks first.</strong> When only one team is available in a window, that is the <em>only</em> chance to interview them during that gap. Visiting a team when they are the sole option makes the best use of judge time and prevents anyone from slipping through to the end of the day uninterviewed. Save the large green windows for teams that have many opportunities throughout the day.</p>
        <p className="help-tip">🎯 Set the expand mode to <strong>≤ 3</strong> (default) so team numbers are shown automatically in the smallest, most critical windows.</p>
      </>
    ),
  },
  {
    id: 'side-by-side',
    title: '4 · Side-by-Side View',
    screenshot: { src: 'side-by-side.png', alt: 'Side-by-side view with scrollable team columns sharing a time axis' },
    content: (
      <>
        <p>The <strong>Side×Side tab</strong> lines up all teams in scrollable columns on a shared time axis so you can spot patterns at a glance.</p>
        <ul>
          <li>Scroll horizontally to see all teams.</li>
          <li>Green blocks are available windows; grey is unavailable.</li>
          <li>Interviewed teams move to the right and their header is crossed out.</li>
        </ul>
        <p className="help-tip">📱 On a phone, scroll left-to-right with your finger.</p>
      </>
    ),
  },
  {
    id: 'refresh',
    title: '5 · Refreshing after delays',
    content: (
      <>
        <p>FRC events run late. Match times shift throughout the day.</p>
        <p>Tap <strong>↻ Refresh</strong> in the header to pull the latest schedule from The Blue Alliance. The timestamp next to the button shows when data was last fetched.</p>
        <p className="help-tip">⚠️ Your <em>Interviewed</em> checkmarks are preserved when you refresh — only the match times update.</p>
      </>
    ),
  },
  {
    id: 'settings',
    title: '6 · Availability settings',
    screenshot: { src: 'settings.png', alt: 'Settings panel showing pre-match buffer, post-match buffer, and minimum interview duration sliders' },
    content: (
      <>
        <p>Tap <strong>⚙ Settings</strong> to tune how availability is calculated.</p>
        <ul>
          <li><strong>Pre-match buffer</strong> — how many minutes before a match the team is considered unavailable (default 10 min). Teams often head to queue early.</li>
          <li><strong>Post-match buffer</strong> — how many minutes after a match the team needs in the pit before they are available (default 5 min).</li>
          <li><strong>Min interview window</strong> — the shortest block that counts as a real opportunity (default 15 min). Shorter gaps are treated as unavailable.</li>
        </ul>
        <p className="help-tip">🔧 Changes take effect immediately — all views update without a re-fetch.</p>
      </>
    ),
  },
]

export default function HelpPanel({ onClose }) {
  return (
    <div
      className="help-overlay"
      role="dialog"
      aria-modal="true"
      aria-label="Help"
      onClick={e => { if (e.target === e.currentTarget) onClose() }}
    >
      <div className="help-sheet">
        <div className="help-sheet-header">
          <h2>How to use the Pit Judge Scheduler</h2>
          <button className="btn btn-ghost btn-sm" onClick={onClose} aria-label="Close help">✕</button>
        </div>

        {SECTIONS.map(section => (
          <section key={section.id} className="help-section">
            <h3 className="help-section-title">{section.title}</h3>
            <div className="help-section-body">{section.content}</div>
            {section.screenshot && (
              <HelpImage src={section.screenshot.src} alt={section.screenshot.alt} />
            )}
          </section>
        ))}

        <div className="help-footer">
          <p>
            <strong>Updating screenshots</strong> — Screenshots are generated from the live app
            using mock data. After any UI change, run:
          </p>
          <pre className="help-code">npm run screenshots</pre>
          <p>Then commit the updated images in <code>public/screenshots/</code> alongside your code changes.</p>
        </div>

        <button className="btn btn-ghost" style={{ width: '100%', marginTop: '1rem' }} onClick={onClose}>
          Close
        </button>
      </div>
    </div>
  )
}
